name: vps

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: start
        run: |
          echo "=== updating system ==="
          sudo apt update -qq
          
          echo "=== installing tmate ==="
          sudo apt install -y tmate
          
          echo "=== tmate ==="
          tmate -F > /tmp/tmate.log 2>&1 &
          sleep 5
          
