name: vps

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup vps
        run: |
          sudo apt update
          sudo apt install -y tmate
          tmate -F
